### ISSUE TITLE
Error when running in Starrock Helm

### ISSUE THREAD

**Issue by quydx** [StarRocks/airbyte-starrocks#6]
I run this connector with airbyte version 0.60.0 and starrock helm 3.3.0. I got this error `2024-07-17 08:42:19 destination > INFO i.a.i.d.r.InMemoryRecordBufferingStrategy(flushAllBuffers):85 Flushing users: 1000 records (2 MB)
2024-07-17 08:42:19 destination > INFO i.a.i.d.s.DefaultStreamLoader(send):114 Stream loading, label : airbyte__airbyte_tmp_clz_users_72c08bdb-5dba-491d-a3b9-86de7fd4fa5a1721205739869, database : example_db, table : _airbyte_tmp_clz_users, request : PUT http://10.233.64.203:8030/api/example_db/_airbyte_tmp_clz_users/_stream_load HTTP/1.1
2024-07-17 08:42:20 destination > INFO i.a.i.d.s.DefaultStreamLoader(send):124 respons is : HttpResponseProxy{HTTP/1.1 307 Temporary Redirect [content-length: 0, location: http://kube-starrocks-cn-0.kube-starrocks-cn-search.spark.svc.cluster.local:8040/api/example_db/_airbyte_tmp_clz_users/_stream_load, content-type: text/html, connection: keep-alive] [Content-Type: text/html,Content-Length: 0,Chunked: false]}
2024-07-17 08:42:20 destination > INFO i.a.i.d.s.DefaultStreamLoader(send):127 responseBody is : 
2024-07-17 08:42:20 destination > ERROR i.a.i.d.s.DefaultStreamLoader(send):165 error response from stream load: 
2024-07-17 08:42:20 destination > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. io.airbyte.integrations.destination.starrocks.exception.StreamLoadFailException: Stream load failed because of unknown exception, db: example_db, table: _airbyte_tmp_clz_users, label: airbyte__airbyte_tmp_clz_users_72c08bdb-5dba-491d-a3b9-86de7fd4fa5a1721205739869
        at io.airbyte.integrations.destination.starrocks.DefaultStreamLoader.send(DefaultStreamLoader.java:168) ~[io.airbyte.airbyte-integrations.connectors-destination-starrocks-0.50.27.jar:?]
        at io.airbyte.integrations.destination.starrocks.StarRocksBufferedConsumerFactory.lambda$recordWriterFunction$2(StarRocksBufferedConsumerFactory.java:100) ~[io.airbyte.airbyte-integrations.connectors-destination-starrocks-0.50.27.jar:?]
        at io.airbyte.integrations.destination.record_buffer.InMemoryRecordBufferingStrategy.flushAllBuffers(InMemoryRecordBufferingStrategy.java:87) ~[io.airbyte.airbyte-integrations.bases-base-java-0.50.27.jar:?]
        at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:298) ~[io.airbyte.airbyte-integrations.bases-base-java-0.50.27.jar:?]
        at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82) ~[io.airbyte.airbyte-integrations.bases-base-java-0.50.27.jar:?]
        at io.airbyte.integrations.base.Destination$ShimToSerializedAirbyteMessageConsumer.close(Destination.java:96) ~[io.airbyte.airbyte-integrations.bases-base-java-0.50.27.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:188) ~[io.airbyte.airbyte-integrations.bases-base-java-0.50.27.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) ~[io.airbyte.airbyte-integrations.bases-base-java-0.50.27.jar:?]
        at io.airbyte.integrations.destination.starrocks.StarRocksDestination.main(StarRocksDestination.java:51) ~[io.airbyte.airbyte-integrations.connectors-destination-starrocks-0.50.27.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.airbyte.integrations.destination.starrocks.StreamLoadResponse$StreamLoadResponseBody.getStatus()" because "streamLoadBody" is null
        at io.airbyte.integrations.destination.starrocks.DefaultStreamLoader.send(DefaultStreamLoader.java:134) ~[io.airbyte.airbyte-integrations.connectors-destination-starrocks-0.50.27.jar:?]
        ... 8 more
Stack Trace: io.airbyte.integrations.destination.starrocks.exception.StreamLoadFailException: Stream load failed because of unknown exception, db: example_db, table: _airbyte_tmp_clz_users, label: airbyte__airbyte_tmp_clz_users_72c08bdb-5dba-491d-a3b9-86de7fd4fa5a1721205739869
        at io.airbyte.integrations.destination.starrocks.DefaultStreamLoader.send(DefaultStreamLoader.java:168)
        at io.airbyte.integrations.destination.starrocks.StarRocksBufferedConsumerFactory.lambda$recordWriterFunction$2(StarRocksBufferedConsumerFactory.java:100)
        at io.airbyte.integrations.destination.record_buffer.InMemoryRecordBufferingStrategy.flushAllBuffers(InMemoryRecordBufferingStrategy.java:87)
        at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:298)
        at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82)
        at io.airbyte.integrations.base.Destination$ShimToSerializedAirbyteMessageConsumer.close(Destination.java:96)
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:188)
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125)
        at io.airbyte.integrations.destination.starrocks.StarRocksDestination.main(StarRocksDestination.java:51)
Caused by: java.lang.NullPointerException: Cannot invoke "io.airbyte.integrations.destination.starrocks.StreamLoadResponse$StreamLoadResponseBody.getStatus()" because "streamLoadBody" is null
        at io.airbyte.integrations.destination.starrocks.DefaultStreamLoader.send(DefaultStreamLoader.java:134)
        ... 8 more`
seems the connector try to put request to starrock but it got Redirect message, respons is : HttpResponseProxy{HTTP/1.1 307 Temporary Redirect [content-length: 0, location: http://kube-starrocks-cn-0.kube-starrocks-cn-search.spark.svc.cluster.local:8040/api/example_db/_airbyte_tmp_clz_users/_stream_load, content-type: text/html, connection: keep-alive] [Content-Type: text/html,Content-Length: 0,Chunked: false]}. So it can not parse the reponse. Do you have solution for this issue?

**Comment by quydx** [comment]
the location of codes that raises error is 
```
 try (CloseableHttpClient client = HttpClients.custom().setRedirectStrategy(
                new DefaultRedirectStrategy()).build();
        ) {
            long startNanoTime = System.nanoTime();
            try (CloseableHttpResponse response = client.execute(httpPut)) {
                LOG.info("respons is : {}", response);
                HttpEntity responseEntity = response.getEntity();
                responseBody = EntityUtils.toString(responseEntity);
                LOG.info("responseBody is : {}", responseBody);
            }
            StreamLoadResponse streamLoadResponse = new StreamLoadResponse();
            StreamLoadResponse.StreamLoadResponseBody streamLoadBody
                    = JSON.parseObject(responseBody, StreamLoadResponse.StreamLoadResponseBody.class);
            streamLoadResponse.setBody(streamLoadBody);

            String status = streamLoadBody.getStatus();
```
